#!/bin/bash

# Array de frases geek con emojis
phrases=(
        "💻 There are 10 types of people in the world: those who understand binary and those who don't.",
        "🔁 To understand recursion, you must first understand recursion.",
        "🐛 A bug in the hand is worth two in the code.",
        "☕ Programmer: A machine that turns coffee into code.",
        "🐞 It's not a bug – it's an undocumented feature!",
        "🌐 In a world without fences and walls, who needs Gates and Windows?",
        "🎨 Beware of geeks bearing .gifs.",
        "🌑 Why do programmers prefer dark mode? Because light attracts bugs.",
        "🛠️ First, solve the problem. Then, write the code.",
        "🏡 There’s no place like 127.0.0.1.",
        "🔢 Real programmers count from 0.",
        "🔄 Git happens.",
        "📦 If at first you don't succeed, call it version 1.0.",
        "🛋️ I'm not lazy, I'm just in energy-saving mode.",
        "🧠 Coding is 90% understanding why it doesn’t work and 10% writing new bugs.",
        "📣 Talk is cheap. Show me the code. — Linus Torvalds",
        "⛪ Software and cathedrals are much the same — first we build them, then we pray.",
        "⏳ Weeks of coding can save you hours of planning.",
        "☕ Programmers are tools for converting caffeine into code.",
        "🧮 The best thing about a boolean is even if you are wrong, you are only off by a bit.",
        "⚙️ Automation is good, so long as you know exactly what you are automating.",
        "🧙‍♂️ Any sufficiently advanced technology is indistinguishable from magic.",
        "🧩 Why do Java developers wear glasses? Because they can't C#.",
        "📜 I have not failed. I've just found 10,000 ways that won't work.",
        "🐍 Life is short, you need Python.",
        "👾 404: Joke not found.",
        "🖥️ Computers make very fast, very accurate mistakes.",
        "📚 Knowledge is power. Power corrupts. Study hard. Be evil.",
        "🛡️ Security is just an illusion.",
        "🕵️‍♂️ Hackers do it with fewer permissions.",
        "📝 I would love to change the world, but they won’t give me the source code.",
        "🚀 Hello World, goodbye sanity.",
        "🎯 Aim for simplicity. Complexity is the enemy of progress.",
        "🤖 Artificial intelligence is no match for natural stupidity.",
        "🪤 Backup: A simple process for duplicating your mistakes.",
        "🔒 Passwords are like underwear. Change them often.",
        "🐢 Slow is smooth, smooth is fast. (Applies to coding too.)",
        "💾 Save early, save often.",
        "🎭 If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
        "🧹 Clean code always looks like it was easy to write.",
        "🌪️ Good code is its own best documentation.",
        "👶 First rule of programming: if it works, don't touch it.",
        "💣 Semicolons; the silent killers of JavaScript apps.",
        "🚧 Code is like humor. When you have to explain it, it’s bad.",
        "🧱 Every great software developer you know got there by solving problems they were unqualified to solve until they actually did it.",
        "🐙 Git commit -am 'fixed it' — lies we tell ourselves.",
        "🖇️ Copy-paste is a design pattern.",
        "🏗️ Good architecture starts with understanding the problem, not the solution.",
        "🎢 Programming is like riding a rollercoaster with bugs.",
        "🔭 Always code as if the person who ends up maintaining your code is a violent psychopath who knows where you live.",
        "🦄 Unicorns are just developers who comment their code properly.",
        "📟 Old code never dies; it just gets moved to production.",
        "🛒 If debugging is the art of fixing bugs, then production is where they go shopping.",
        "💸 Technical debt is like financial debt — ignoring it only makes it worse.",
        "🎤 Ship it!",
        "🎩 I'm not a magician, I'm just a developer.",
        "🌈 Code is poetry.",
        "🦖 Programming today is a race between software engineers striving to build bigger and better idiot-proof programs, and the universe trying to produce bigger and better idiots. So far, the universe is winning.",
        "⚡ Coding is the closest thing we have to superpowers.",
        "🏹 Launch early. Optimize later.",
        "🧟‍♂️ Zombie processes: Because sometimes dead things don't stay dead.",
        "🛸 I come in peace... to refactor your code.",
        "🌋 Stack overflow? More like stack eruption!",
        "🕸️ I tangled my logic in a web of callbacks.",
        "🎛️ Segmentation fault: core dumped.",
        "🧙‍♂️ Debugging: Where you stare into the abyss, and the abyss stares back at you.",
        "💔 A compiler error is just a love letter from your machine, asking you to try harder.",
        "🚀 Deploy early, deploy often.",
        "🔍 No, you can't just 'Google it'... oh wait, you can.",
        "🚿 Clean architecture leads to clean minds.",
        "📈 Scaling code is harder than writing it.",
        "📉 Premature optimization is the root of all evil.",
        "🔒 SSL is just a pretty padlock for your broken website.",
        "👻 Ghost bugs: They vanish when you try to debug them.",
        "🧨 Breaking changes should come with a warning label.",
        "🎰 Random failures make debugging fun! (Not.)",
        "📡 Your WiFi signal strength is directly proportional to your patience.",
        "🗿 Ship the MVP, not Mount Rushmore.",
        "📦 Your container has crashed. Would you like to send an error report?",
        "🛞 Rollbacks: Because not every deployment is a success story.",
        "🧲 Docker: Because 'it works on my machine' is not an excuse anymore.",
        "🧹 A dirty repo is a sad repo.",
        "🛀 Relax. It’s just a minor outage. (said no dev ever)",
        "🧠 Always think twice. Then test thrice.",
        "🛸 Deployments never fail — they just reveal hidden problems.",
        "🎨 Your code is your art. Your bugs are your critics.",
        "📺 Streaming errors live from production... because who needs sleep?",
        "🪛 Version 2.0: because Version 1.0 was basically beta.",
        "🍂 Refactor code like you're raking leaves in autumn: patient, thorough, and a little nostalgic.",
        "🛎️ Documentation is like a gym membership: everyone agrees it's good, but nobody uses it.",
        "🎢 Feature creep is a rollercoaster you can’t get off.",
        "💣 Merge conflicts: explosions of frustration.",
        "🌍 Code globally, debug locally.",
        "📣 Stand-ups: when developers pretend they understand project managers.",
        "🍵 Take breaks. Even infinite loops need a timeout.",
        "🐧 Linux: Where if you break it, you get to keep all the pieces.",
        "🛑 Don't deploy on Fridays. Just don't.",
        "🔩 APIs are the glue holding the Internet together — and duct tape.",
        "🗂️ Organize your files, or be organized by entropy.",
        "🔧 Trust in engineers: we fix it till it's broken.",
        "💼 Project managers: The boss battle at the end of the project.",
        "💤 Sleep is for the weak... or the smart.",
        "🎭 Fake it till you make it... but comment your code meanwhile.",
        "🧗 The biggest obstacle to coding is assuming you understand the problem.",
        "🚴‍♂️ Learning to program is like riding a bike — except the bike is on fire, you're on fire, everything is on fire.",
        "🧯 Panic is not a strategy.",
        "🎮 Gamers and coders: Different missions, same love for bugs.",
        "🪄 Bash scripts: when you want magic but can only afford spaghetti.",
        "🍿 Errors are just unexpected plot twists.",
        "💡 Ideas are easy. Execution is everything.",
        "🚪 Stack overflows: the real door to Narnia.",
        "🔋 Battery low. Developer needs coffee.",
        "📑 Code reviews: where hope goes to die.",
        "🎯 Stay focused. Stay sharp. Stay caffeinated.",
        "🏆 Ship it. Then improve it.",
    )

# Obtener el número total de frases
total_phrases=${#phrases[@]}

# Escoger una frase aleatoria
random_index=$(( RANDOM % total_phrases ))
selected_phrase="${phrases[$random_index]}"

# Imprimirla
echo $selected_phrase
